# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "180"
  ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "180"
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "ZirafApp.xcworkspace", scheme: "ZirafApp")
    upload_to_app_store(skip_binary_upload: true, skip_metadata: true)
  end

  lane :beta do
    get_certificates
    get_provisioning_profile
	scheme = "ZirafApp"

	gym(
      scheme: scheme,
      export_method: "app-store",
      configuration: "Release",
    )

    pilot(
      skip_submission: false,
      distribute_external: false,
      skip_waiting_for_build_processing: true
    )
  end
end
