/**
 * APP CONFIG DATA
 */
export const SET_APP_STATE_DATA = 'SET_APP_STATE_DATA';
export const CLEAR_APP_STATE_DATA = 'CLEAR_APP_STATE_DATA';

/**
 * APP CONFIG
 */
export const FETCH_APP_CONFIG_REQUEST = 'FETCH_APP_CONFIG_REQUEST';
export const FETCH_APP_CONFIG_REQUEST_SUCCESS =
	'FETCH_APP_CONFIG_REQUEST_SUCCESS';
export const FETCH_APP_CONFIG_REQUEST_ERROR = 'FETCH_APP_CONFIG_REQUEST_ERROR';

/**
 * AUTOCOMPLETE
 */
export const FETCH_AUTOCOMPLETE_REQUEST = 'FETCH_AUTOCOMPLETE_REQUEST';
export const FETCH_AUTOCOMPLETE_REQUEST_SUCCESS = 'FETCH_AUTOCOMPLETE_REQUEST_SUCCESS';
export const FETCH_AUTOCOMPLETE_REQUEST_ERROR = 'FETCH_AUTOCOMPLETE_REQUEST_ERROR';

/**
 * MOMENT LIST
 */
export const FETCH_MOMENT_LIST_REQUEST = 'FETCH_MOMENT_LIST_REQUEST';
export const FETCH_MOMENT_LIST_REQUEST_SUCCESS =
	'FETCH_MOMENT_LIST_REQUEST_SUCCESS';
export const FETCH_MOMENT_LIST_REQUEST_ERROR =
	'FETCH_MOMENT_LIST_REQUEST_ERROR';

/**
 * MOMENT RESTAURANTS
 */
export const FETCH_MOMENT_RESTAURANTS_REQUEST =
	'FETCH_MOMENT_RESTAURANTS_REQUEST';
export const FETCH_MOMENT_RESTAURANTS_REQUEST_SUCCESS =
	'FETCH_MOMENT_RESTAURANTS_REQUEST_SUCCESS';
export const FETCH_MOMENT_RESTAURANTS_REQUEST_ERROR =
	'FETCH_MOMENT_RESTAURANTS_REQUEST_ERROR';

/**
 * DISCOUNT RESTAURANT
 */
export const FETCH_DISCOUNT_RESTAURANTS_REQUEST =
	'FETCH_DISCOUNT_RESTAURANTS_REQUEST';
export const FETCH_DISCOUNT_RESTAURANTS_REQUEST_SUCCESS =
	'FETCH_DISCOUNT_RESTAURANTS_REQUEST_SUCCESS';
export const FETCH_DISCOUNT_RESTAURANTS_REQUEST_ERROR =
	'FETCH_DISCOUNT_RESTAURANTS_REQUEST_ERROR';

/**
 * RESTAURANT LIST
 */
export const FETCH_RESTAURANT_LIST_REQUEST = 'FETCH_RESTAURANT_LIST_REQUEST';
export const FETCH_RESTAURANT_LIST_REQUEST_SUCCESS =
	'FETCH_RESTAURANT_LIST_REQUEST_SUCCESS';
export const FETCH_RESTAURANT_LIST_REQUEST_ERROR =
	'FETCH_RESTAURANT_LIST_REQUEST_ERROR';

/**
 * FAVOURITE RESTAURANT
 */
export const FETCH_FAVOURITE_RESTAURANTS_REQUEST =
	'FETCH_FAVOURITE_RESTAURANTS_REQUEST';
export const FETCH_FAVOURITE_RESTAURANTS_REQUEST_SUCCESS =
	'FETCH_FAVOURITE_RESTAURANTS_REQUEST_SUCCESS';
export const FETCH_FAVOURITE_RESTAURANTS_REQUEST_ERROR =
	'FETCH_FAVOURITE_RESTAURANTS_REQUEST_ERROR';

/**
 * RESTAURANT DETAIL
 */
export const FETCH_RESTAURANT_DETAIL_REQUEST =
	'FETCH_RESTAURANT_DETAIL_REQUEST';
export const FETCH_RESTAURANT_DETAIL_REQUEST_SUCCESS =
	'FETCH_RESTAURANT_DETAIL_REQUEST_SUCCESS';
export const FETCH_RESTAURANT_DETAIL_REQUEST_ERROR =
	'FETCH_RESTAURANT_DETAIL_REQUEST_ERROR';
export const CLEAR_RESTAURANT_DETAIL_REQUEST =
	'CLEAR_RESTAURANT_DETAIL_REQUEST';

/**
 * RESTAURANT REVIEW
 */
export const FETCH_RESTAURANT_REVIEW_REQUEST =
	'FETCH_RESTAURANT_REVIEW_REQUEST';
export const FETCH_RESTAURANT_REVIEW_REQUEST_SUCCESS =
	'FETCH_RESTAURANT_REVIEW_REQUEST_SUCCESS';
export const FETCH_RESTAURANT_REVIEW_REQUEST_ERROR =
	'FETCH_RESTAURANT_REVIEW_REQUEST_ERROR';

/**
 * RESTAURANT MENU
 */
export const FETCH_RESTAURANT_MENU_REQUEST = 'FETCH_RESTAURANT_MENU_REQUEST';
export const FETCH_RESTAURANT_MENU_REQUEST_SUCCESS =
	'FETCH_RESTAURANT_MENU_REQUEST_SUCCESS';
export const FETCH_RESTAURANT_MENU_REQUEST_ERROR =
	'FETCH_RESTAURANT_MENU_REQUEST_ERROR';

/**
 * RESTAURANT AUTOCOMPLETE
 */
export const FETCH_RESTAURANT_AUTOCOMPLETE_REQUEST =
	'FETCH_RESTAURANT_AUTOCOMPLETE_REQUEST';
export const FETCH_RESTAURANT_AUTOCOMPLETE_REQUEST_SUCCESS =
	'FETCH_RESTAURANT_AUTOCOMPLETE_REQUEST_SUCCESS';
export const FETCH_RESTAURANT_AUTOCOMPLETE_REQUEST_ERROR =
	'FETCH_RESTAURANT_AUTOCOMPLETE_REQUEST_ERROR';

/**
 * LOCATION LIST
 */
export const FETCH_LOCATION_LIST_REQUEST = 'FETCH_LOCATION_LIST_REQUEST';
export const FETCH_LOCATION_LIST_REQUEST_SUCCESS =
	'FETCH_LOCATION_LIST_REQUEST_SUCCESS';
export const FETCH_LOCATION_LIST_REQUEST_ERROR =
	'FETCH_LOCATION_LIST_REQUEST_ERROR';

/**
 * USER DETAIL
 */
export const FETCH_USER_DETAIL_REQUEST = 'FETCH_USER_DETAIL_REQUEST';
export const FETCH_USER_DETAIL_REQUEST_SUCCESS =
	'FETCH_USER_DETAIL_REQUEST_SUCCESS';
export const FETCH_USER_DETAIL_REQUEST_ERROR =
	'FETCH_USER_DETAIL_REQUEST_ERROR';
export const CLEAR_USER_DETAIL_REQUEST = 'CLEAR_USER_DETAIL_REQUEST';

/**
 * ZIRAFER LIST
 */
export const FETCH_ZIRAFER_LIST_REQUEST = 'FETCH_ZIRAFER_LIST_REQUEST';
export const FETCH_ZIRAFER_LIST_REQUEST_SUCCESS =
	'FETCH_ZIRAFER_LIST_REQUEST_SUCCESS';
export const FETCH_ZIRAFER_LIST_REQUEST_ERROR =
	'FETCH_ZIRAFER_LIST_REQUEST_ERROR';

/**
 * ZIRAFER DETAIL
 */
export const FETCH_ZIRAFER_DETAIL_REQUEST = 'FETCH_ZIRAFER_DETAIL_REQUEST';
export const FETCH_ZIRAFER_DETAIL_REQUEST_SUCCESS =
	'FETCH_ZIRAFER_DETAIL_REQUEST_SUCCESS';
export const FETCH_ZIRAFER_DETAIL_REQUEST_ERROR =
	'FETCH_ZIRAFER_DETAIL_REQUEST_ERROR';
export const CLEAR_ZIRAFER_DETAIL_REQUEST = 'CLEAR_ZIRAFER_DETAIL_REQUEST';
